server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
  neo4j:
    url: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Neo4j
management:
  server:
    port: 8082
    address: 127.0.0.1